namespace Linko.LinkoExchange.Core.Enum
{
    public enum SettingType
    {
        FailedPasswordAttemptMaxCount,
        FailedKBQAttemptMaxCount,
        InvitationExpiredHours,
        PasswordChangeRequiredDays,
        PasswordHistoryMaxCount,
        TimeZone,
        ReportRepudiatedDays,
        ComplianceDeterminationDate,
        MassLoadingConversionFactorPounds,
        MassLoadingResultToUseLessThanSign,
        MassLoadingCalculationDecimalPlaces,
        EmailContactInfoName,
        EmailContactInfoPhone,
        EmailContactInfoEmailAddress,
        AuthorityUserLicenseTotalCount,
        IndustryLicenseTotalCount,
        UserPerIndustryMaxCount,
        ResultQualifierValidValues,
        FlowUnitValidValues,
        SampleNameCreationRule,
        SendToCtsDatabaseServerName,
        SendToCtsDatabaseName,
        ReportElementTypeIdForIndustryFileUpload
    }
}