//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linko.LinkoExchange.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linko.LinkoExchange.Core.Resources.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Locked.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Reset Expired.
        /// </summary>
        public static string AccountResetExpired {
            get {
                return ResourceManager.GetString("AccountResetExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Reset Initiated.
        /// </summary>
        public static string AccountResetInitiated {
            get {
                return ResourceManager.GetString("AccountResetInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Reset Required.
        /// </summary>
        public static string AccountResetRequired {
            get {
                return ResourceManager.GetString("AccountResetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Reset Successful.
        /// </summary>
        public static string AccountResetSuccessful {
            get {
                return ResourceManager.GetString("AccountResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and we&apos;ll send a password reset link to the email address we have on file..
        /// </summary>
        public static string BoxTitleForgotPassword {
            get {
                return ResourceManager.GetString("BoxTitleForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address and we&apos;ll send it to you..
        /// </summary>
        public static string BoxTitleForgotUserName {
            get {
                return ResourceManager.GetString("BoxTitleForgotUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Information.
        /// </summary>
        public static string BoxTitleIndustryInformation {
            get {
                return ResourceManager.GetString("BoxTitleIndustryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Authority Portal.
        /// </summary>
        public static string BoxTitleSelectAuthority {
            get {
                return ResourceManager.GetString("BoxTitleSelectAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Industry Portal.
        /// </summary>
        public static string BoxTitleSelectIndustry {
            get {
                return ResourceManager.GetString("BoxTitleSelectIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Report Packages.
        /// </summary>
        public static string Breadcrumb_All {
            get {
                return ResourceManager.GetString("Breadcrumb_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Package - Draft.
        /// </summary>
        public static string Breadcrumb_Draft {
            get {
                return ResourceManager.GetString("Breadcrumb_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Package - Ready to Submit.
        /// </summary>
        public static string Breadcrumb_ReadyToSubmit {
            get {
                return ResourceManager.GetString("Breadcrumb_ReadyToSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Package - Repudiated.
        /// </summary>
        public static string Breadcrumb_Repudiated {
            get {
                return ResourceManager.GetString("Breadcrumb_Repudiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Package Repudiations Pending Review.
        /// </summary>
        public static string Breadcrumb_RepudiatedPendingReview {
            get {
                return ResourceManager.GetString("Breadcrumb_RepudiatedPendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Package - Submitted.
        /// </summary>
        public static string Breadcrumb_Submitted {
            get {
                return ResourceManager.GetString("Breadcrumb_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Package Submissions Pending Review.
        /// </summary>
        public static string Breadcrumb_SubmittedPendingReview {
            get {
                return ResourceManager.GetString("Breadcrumb_SubmittedPendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string ButtonGo {
            get {
                return ResourceManager.GetString("ButtonGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ButtonProfile {
            get {
                return ResourceManager.GetString("ButtonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ButtonResetPassword {
            get {
                return ResourceManager.GetString("ButtonResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ButtonSend {
            get {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string ButtonSignOut {
            get {
                return ResourceManager.GetString("ButtonSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email Address.
        /// </summary>
        public static string ChangEmailAddress {
            get {
                return ResourceManager.GetString("ChangEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Signatory Agreement.
        /// </summary>
        public static string DownloadSignatoryAgreement {
            get {
                return ResourceManager.GetString("DownloadSignatoryAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Changed.
        /// </summary>
        public static string EmailChanged {
            get {
                return ResourceManager.GetString("EmailChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot User Name.
        /// </summary>
        public static string ForgotUserName {
            get {
                return ResourceManager.GetString("ForgotUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Proofed.
        /// </summary>
        public static string IdentityProofed {
            get {
                return ResourceManager.GetString("IdentityProofed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Deleted.
        /// </summary>
        public static string InviteDeleted {
            get {
                return ResourceManager.GetString("InviteDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Sent.
        /// </summary>
        public static string InviteSent {
            get {
                return ResourceManager.GetString("InviteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KBQ Changed.
        /// </summary>
        public static string KBQChanged {
            get {
                return ResourceManager.GetString("KBQChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkoExchange.
        /// </summary>
        public static string LinkoExchange {
            get {
                return ResourceManager.GetString("LinkoExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Account Lock.
        /// </summary>
        public static string ManualAccountLock {
            get {
                return ResourceManager.GetString("ManualAccountLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Account Unlock.
        /// </summary>
        public static string ManualAccountUnlock {
            get {
                return ResourceManager.GetString("ManualAccountUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Association.
        /// </summary>
        public static string NoAssociation {
            get {
                return ResourceManager.GetString("NoAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Lockout.
        /// </summary>
        public static string PasswordLockout {
            get {
                return ResourceManager.GetString("PasswordLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Expired.
        /// </summary>
        public static string PasswordResetExpired {
            get {
                return ResourceManager.GetString("PasswordResetExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Report.
        /// </summary>
        public static string ReadyToReport {
            get {
                return ResourceManager.GetString("ReadyToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Submit.
        /// </summary>
        public static string ReadyToSubmit {
            get {
                return ResourceManager.GetString("ReadyToSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Approved.
        /// </summary>
        public static string RegistrationApproved {
            get {
                return ResourceManager.GetString("RegistrationApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Denied.
        /// </summary>
        public static string RegistrationDenied {
            get {
                return ResourceManager.GetString("RegistrationDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Pending.
        /// </summary>
        public static string RegistrationPending {
            get {
                return ResourceManager.GetString("RegistrationPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported.
        /// </summary>
        public static string Reported {
            get {
                return ResourceManager.GetString("Reported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repudiated.
        /// </summary>
        public static string Repudiated {
            get {
                return ResourceManager.GetString("Repudiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repudiated Pending Review.
        /// </summary>
        public static string RepudiatedPendingReview {
            get {
                return ResourceManager.GetString("RepudiatedPendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Change.
        /// </summary>
        public static string RoleChange {
            get {
                return ResourceManager.GetString("RoleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Event Type.
        /// </summary>
        public static string SampleEventType {
            get {
                return ResourceManager.GetString("SampleEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Event Type + Collection Method.
        /// </summary>
        public static string SampleEventTypeCollectionMethod {
            get {
                return ResourceManager.GetString("SampleEventTypeCollectionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Reason.
        /// </summary>
        public static string SelectReason {
            get {
                return ResourceManager.GetString("SelectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatory Granted.
        /// </summary>
        public static string SignatoryGranted {
            get {
                return ResourceManager.GetString("SignatoryGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatory Pending.
        /// </summary>
        public static string SignatoryPending {
            get {
                return ResourceManager.GetString("SignatoryPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatory Revoked.
        /// </summary>
        public static string SignatoryRevoked {
            get {
                return ResourceManager.GetString("SignatoryRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Failed.
        /// </summary>
        public static string SignFailed {
            get {
                return ResourceManager.GetString("SignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQ Changed.
        /// </summary>
        public static string SQChanged {
            get {
                return ResourceManager.GetString("SQChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted Pending Review.
        /// </summary>
        public static string SubmittedPendingReview {
            get {
                return ResourceManager.GetString("SubmittedPendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string TitleForgotPassword {
            get {
                return ResourceManager.GetString("TitleForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot User Name.
        /// </summary>
        public static string TitleForgotUserName {
            get {
                return ResourceManager.GetString("TitleForgotUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Details.
        /// </summary>
        public static string TitleIndustryDetails {
            get {
                return ResourceManager.GetString("TitleIndustryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Based Question.
        /// </summary>
        public static string TitleKBQChanllenge {
            get {
                return ResourceManager.GetString("TitleKBQChanllenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkoExchange Sign In.
        /// </summary>
        public static string TitleLinkoExchangeSignIn {
            get {
                return ResourceManager.GetString("TitleLinkoExchangeSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Signatory Rights.
        /// </summary>
        public static string TitleRequestSignatoryRight {
            get {
                return ResourceManager.GetString("TitleRequestSignatoryRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string TitleResetPassword {
            get {
                return ResourceManager.GetString("TitleResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Access.
        /// </summary>
        public static string UserAccess {
            get {
                return ResourceManager.GetString("UserAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Disabled.
        /// </summary>
        public static string UserDisabled {
            get {
                return ResourceManager.GetString("UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
