//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linko.LinkoExchange.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linko.LinkoExchange.Core.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not associated with any active Organization.  Please contact your Authority for assistance..
        /// </summary>
        public static string AccountIsNotAssociated {
            get {
                return ResourceManager.GetString("AccountIsNotAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked. Please contact your Authority for assistance..
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been reset and re-registration is required.  Please contact your Authority for assistance..
        /// </summary>
        public static string AccountReset {
            get {
                return ResourceManager.GetString("AccountReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found..
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of login attempts exceeded. Use Forgot Password to reset your password..
        /// </summary>
        public static string ExceedMaximumLoginAttempt {
            get {
                return ResourceManager.GetString("ExceedMaximumLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed..
        /// </summary>
        public static string PasswordChangeSucceed {
            get {
                return ResourceManager.GetString("PasswordChangeSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has expired..
        /// </summary>
        public static string PasswordExpired {
            get {
                return ResourceManager.GetString("PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Registration has not yet been approved..
        /// </summary>
        public static string RegistrationApprovalPending {
            get {
                return ResourceManager.GetString("RegistrationApprovalPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but your session has timed out. You&apos;ll be redirected to the Sign In page in 30 seconds....
        /// </summary>
        public static string SessionTimeOutPopupMessage {
            get {
                return ResourceManager.GetString("SessionTimeOutPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is disabled. Please contact your Authority for assistance..
        /// </summary>
        public static string UserAccountDisabled {
            get {
                return ResourceManager.GetString("UserAccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name not found..
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform the action. See error messages below..
        /// </summary>
        public static string ValidationSummaryHeaderText {
            get {
                return ResourceManager.GetString("ValidationSummaryHeaderText", resourceCulture);
            }
        }
    }
}
